In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../nba-stats-csv/player_stats_total.csv')

In [3]:
df_A = df.sample(10)
df_B = df.sample(10)

In [4]:
df_A

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
120,Mike Miller,2034,2011-12,39.0,32.0,752.050,91.0,209.0,53.0,2.0,5.0,22.0,106.0,42.0,30.0,14.0,6.0,237.0
1872,Trevor Booker,202344,2013-14,72.0,26.0,1553.440,222.0,403.0,0.0,47.0,76.0,149.0,230.0,64.0,58.0,41.0,45.0,491.0
2598,Kelly Oubre Jr.,1626162,2016-17,79.0,21.0,1605.190,186.0,442.0,54.0,75.0,99.0,61.0,200.0,47.0,50.0,58.0,17.0,501.0
1823,Luke Babbitt,202337,2010-11,24.0,22.0,137.255,15.0,55.0,3.0,3.0,9.0,6.0,24.0,6.0,8.0,2.0,2.0,36.0
615,Tony Allen,2754,2005-06,51.0,24.0,978.052,129.0,274.0,11.0,100.0,134.0,32.0,79.0,67.0,67.0,51.0,18.0,369.0
1408,Michael Beasley,201563,2010-11,73.0,22.0,2361.480,561.0,1246.0,60.0,219.0,291.0,118.0,291.0,158.0,195.0,54.0,52.0,1401.0
89,Metta World Peace,1897,2013-14,29.0,34.0,388.137,56.0,141.0,17.0,10.0,16.0,18.0,41.0,17.0,19.0,24.0,8.0,139.0
2493,Nerlens Noel,203457,2014-15,75.0,21.0,2311.270,302.0,653.0,0.0,140.0,230.0,185.0,426.0,128.0,146.0,133.0,142.0,744.0
72,Jason Terry,1891,2014-15,77.0,37.0,1641.180,188.0,446.0,126.0,39.0,48.0,15.0,106.0,147.0,74.0,66.0,19.0,541.0
2071,Anthony Davis,203076,2015-16,61.0,23.0,2164.240,560.0,1136.0,35.0,326.0,430.0,130.0,497.0,116.0,121.0,78.0,125.0,1481.0

In [5]:
df_B

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
675,Brandon Bass,101138,2008-09,81.0,24.0,1574.3800,252.0,508.0,0.0,182.0,210.0,129.0,238.0,43.0,86.0,27.0,55.0,686.0
1716,Derrick Favors,202324,2010-11,78.0,19.0,1535.9900,215.0,416.0,0.0,103.0,173.0,171.0,241.0,39.0,77.0,29.0,68.0,533.0
1990,Kyrie Irving,202681,2015-16,53.0,24.0,1667.4400,394.0,879.0,84.0,169.0,191.0,44.0,113.0,250.0,124.0,56.0,18.0,1041.0
1502,DeMar DeRozan,201942,2011-12,63.0,22.0,2205.6100,381.0,903.0,24.0,268.0,331.0,40.0,171.0,128.0,123.0,48.0,17.0,1054.0
2671,Davis Bertans,202722,2016-17,67.0,24.0,807.6080,103.0,234.0,69.0,28.0,34.0,22.0,76.0,46.0,32.0,20.0,28.0,303.0
1681,Al-Farouq Aminu,202329,2010-11,81.0,20.0,1451.5400,160.0,406.0,45.0,92.0,119.0,75.0,192.0,60.0,103.0,59.0,25.0,457.0
500,Beno Udrih,2757,2016-17,39.0,34.0,560.2030,92.0,197.0,11.0,32.0,34.0,6.0,51.0,131.0,36.0,13.0,0.0,227.0
474,Anderson Varejao,2760,2016-17,14.0,34.0,91.8617,5.0,14.0,0.0,8.0,11.0,12.0,15.0,10.0,8.0,3.0,3.0,18.0
1689,Avery Bradley,202340,2011-12,64.0,21.0,1368.3500,200.0,402.0,22.0,62.0,78.0,34.0,81.0,87.0,75.0,43.0,12.0,484.0
2339,Otto Porter Jr.,203490,2016-17,80.0,23.0,2605.1600,414.0,803.0,148.0,99.0,119.0,118.0,396.0,121.0,44.0,116.0,42.0,1075.0

In [6]:
pd.concat([df_A, df_B])

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
120,Mike Miller,2034,2011-12,39.0,32.0,752.0500,91.0,209.0,53.0,2.0,5.0,22.0,106.0,42.0,30.0,14.0,6.0,237.0
1872,Trevor Booker,202344,2013-14,72.0,26.0,1553.4400,222.0,403.0,0.0,47.0,76.0,149.0,230.0,64.0,58.0,41.0,45.0,491.0
2598,Kelly Oubre Jr.,1626162,2016-17,79.0,21.0,1605.1900,186.0,442.0,54.0,75.0,99.0,61.0,200.0,47.0,50.0,58.0,17.0,501.0
1823,Luke Babbitt,202337,2010-11,24.0,22.0,137.2550,15.0,55.0,3.0,3.0,9.0,6.0,24.0,6.0,8.0,2.0,2.0,36.0
615,Tony Allen,2754,2005-06,51.0,24.0,978.0520,129.0,274.0,11.0,100.0,134.0,32.0,79.0,67.0,67.0,51.0,18.0,369.0
1408,Michael Beasley,201563,2010-11,73.0,22.0,2361.4800,561.0,1246.0,60.0,219.0,291.0,118.0,291.0,158.0,195.0,54.0,52.0,1401.0
89,Metta World Peace,1897,2013-14,29.0,34.0,388.1370,56.0,141.0,17.0,10.0,16.0,18.0,41.0,17.0,19.0,24.0,8.0,139.0
2493,Nerlens Noel,203457,2014-15,75.0,21.0,2311.2700,302.0,653.0,0.0,140.0,230.0,185.0,426.0,128.0,146.0,133.0,142.0,744.0
72,Jason Terry,1891,2014-15,77.0,37.0,1641.1800,188.0,446.0,126.0,39.0,48.0,15.0,106.0,147.0,74.0,66.0,19.0,541.0
2071,Anthony Davis,203076,2015-16,61.0,23.0,2164.2400,560.0,1136.0,35.0,326.0,430.0,130.0,497.0,116.0,121.0,78.0,125.0,1481.0
675,Brandon Bass,101138,2008-09,81.0,24.0,1574.3800,252.0,508.0,0.0,182.0,210.0,129.0,238.0,43.0,86.0,27.0,55.0,686.0
1716,Derrick Favors,202324,2010-11,78.0,19.0,1535.9900,215.0,416.0,0.0,103.0,173.0,171.0,241.0,39.0,77.0,29.0,68.0,533.0
1990,Kyrie Irving,202681,2015-16,53.0,24.0,1667.4400,394.0,879.0,84.0,169.0,191.0,44.0,113.0,250.0,124.0,56.0,18.0,1041.0
1502,DeMar DeRozan,201942,2011-12,63.0,22.0,2205.6100,381.0,903.0,24.0,268.0,331.0,40.0,171.0,128.0,123.0,48.0,17.0,1054.0
2671,Davis Bertans,202722,2016-17,67.0,24.0,807.6080,103.0,234.0,69.0,28.0,34.0,22.0,76.0,46.0,32.0,20.0,28.0,303.0
1681,Al-Farouq Aminu,202329,2010-11,81.0,20.0,1451.5400,160.0,406.0,45.0,92.0,119.0,75.0,192.0,60.0,103.0,59.0,25.0,457.0
500,Beno Udrih,2757,2016-17,39.0,34.0,560.2030,92.0,197.0,11.0,32.0,34.0,6.0,51.0,131.0,36.0,13.0,0.0,227.0
474,Anderson Varejao,2760,2016-17,14.0,34.0,91.8617,5.0,14.0,0.0,8.0,11.0,12.0,15.0,10.0,8.0,3.0,3.0,18.0
1689,Avery Bradley,202340,2011-12,64.0,21.0,1368.3500,200.0,402.0,22.0,62.0,78.0,34.0,81.0,87.0,75.0,43.0,12.0,484.0
2339,Otto Porter Jr.,203490,2016-17,80.0,23.0,2605.1600,414.0,803.0,148.0,99.0,119.0,118.0,396.0,121.0,44.0,116.0,42.0,1075.0

In [7]:
# Concat requires same columns in dfs being concatenated

In [8]:
# Append is similar but is called directly on df object

In [9]:
df_A.append(df_B)

,player_name,player_id,season_id,gp,age,min,fgm,fga,fg3m,ftm,fta,oreb,dreb,ast,tov,stl,blk,pts
120,Mike Miller,2034,2011-12,39.0,32.0,752.0500,91.0,209.0,53.0,2.0,5.0,22.0,106.0,42.0,30.0,14.0,6.0,237.0
1872,Trevor Booker,202344,2013-14,72.0,26.0,1553.4400,222.0,403.0,0.0,47.0,76.0,149.0,230.0,64.0,58.0,41.0,45.0,491.0
2598,Kelly Oubre Jr.,1626162,2016-17,79.0,21.0,1605.1900,186.0,442.0,54.0,75.0,99.0,61.0,200.0,47.0,50.0,58.0,17.0,501.0
1823,Luke Babbitt,202337,2010-11,24.0,22.0,137.2550,15.0,55.0,3.0,3.0,9.0,6.0,24.0,6.0,8.0,2.0,2.0,36.0
615,Tony Allen,2754,2005-06,51.0,24.0,978.0520,129.0,274.0,11.0,100.0,134.0,32.0,79.0,67.0,67.0,51.0,18.0,369.0
1408,Michael Beasley,201563,2010-11,73.0,22.0,2361.4800,561.0,1246.0,60.0,219.0,291.0,118.0,291.0,158.0,195.0,54.0,52.0,1401.0
89,Metta World Peace,1897,2013-14,29.0,34.0,388.1370,56.0,141.0,17.0,10.0,16.0,18.0,41.0,17.0,19.0,24.0,8.0,139.0
2493,Nerlens Noel,203457,2014-15,75.0,21.0,2311.2700,302.0,653.0,0.0,140.0,230.0,185.0,426.0,128.0,146.0,133.0,142.0,744.0
72,Jason Terry,1891,2014-15,77.0,37.0,1641.1800,188.0,446.0,126.0,39.0,48.0,15.0,106.0,147.0,74.0,66.0,19.0,541.0
2071,Anthony Davis,203076,2015-16,61.0,23.0,2164.2400,560.0,1136.0,35.0,326.0,430.0,130.0,497.0,116.0,121.0,78.0,125.0,1481.0
675,Brandon Bass,101138,2008-09,81.0,24.0,1574.3800,252.0,508.0,0.0,182.0,210.0,129.0,238.0,43.0,86.0,27.0,55.0,686.0
1716,Derrick Favors,202324,2010-11,78.0,19.0,1535.9900,215.0,416.0,0.0,103.0,173.0,171.0,241.0,39.0,77.0,29.0,68.0,533.0
1990,Kyrie Irving,202681,2015-16,53.0,24.0,1667.4400,394.0,879.0,84.0,169.0,191.0,44.0,113.0,250.0,124.0,56.0,18.0,1041.0
1502,DeMar DeRozan,201942,2011-12,63.0,22.0,2205.6100,381.0,903.0,24.0,268.0,331.0,40.0,171.0,128.0,123.0,48.0,17.0,1054.0
2671,Davis Bertans,202722,2016-17,67.0,24.0,807.6080,103.0,234.0,69.0,28.0,34.0,22.0,76.0,46.0,32.0,20.0,28.0,303.0
1681,Al-Farouq Aminu,202329,2010-11,81.0,20.0,1451.5400,160.0,406.0,45.0,92.0,119.0,75.0,192.0,60.0,103.0,59.0,25.0,457.0
500,Beno Udrih,2757,2016-17,39.0,34.0,560.2030,92.0,197.0,11.0,32.0,34.0,6.0,51.0,131.0,36.0,13.0,0.0,227.0
474,Anderson Varejao,2760,2016-17,14.0,34.0,91.8617,5.0,14.0,0.0,8.0,11.0,12.0,15.0,10.0,8.0,3.0,3.0,18.0
1689,Avery Bradley,202340,2011-12,64.0,21.0,1368.3500,200.0,402.0,22.0,62.0,78.0,34.0,81.0,87.0,75.0,43.0,12.0,484.0
2339,Otto Porter Jr.,203490,2016-17,80.0,23.0,2605.1600,414.0,803.0,148.0,99.0,119.0,118.0,396.0,121.0,44.0,116.0,42.0,1075.0

In [10]:
# Merging and Joining Dataframes

In [11]:
df1 = pd.read_csv('../nba-stats-csv/player_general_traditional_per_game_data.csv')
df2 = pd.read_csv('../nba-stats-csv/player_id_player_name.csv')

In [12]:
df1.head(5)

,player_id,season_id,gp,age,min,fgm,fga,fg_pct,fg3m,fg3a,...,ftm,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts
0,471,1996-97,41.0,NaN,13.3,1.1,3.3,0.331,0.2,0.7,...,1.0,1.2,0.875,0.7,1.8,1.4,0.8,0.2,0.3,3.4
1,920,1996-97,83.0,33.0,30.8,2.8,5.8,0.483,0.0,0.2,...,1.5,2.4,0.650,2.7,5.2,0.8,0.9,0.8,0.2,7.2
2,243,1996-97,83.0,24.0,20.4,1.8,4.4,0.411,0.5,1.2,...,1.1,1.3,0.836,0.5,2.2,1.9,1.1,0.9,0.3,5.2
3,1425,1996-97,33.0,25.0,17.8,2.6,4.5,0.574,0.0,0.0,...,1.0,1.5,0.673,1.9,2.5,0.5,1.0,0.5,0.9,6.2
4,768,1996-97,47.0,27.0,11.1,1.4,3.8,0.374,0.0,0.1,...,1.1,1.8,0.643,0.7,1.3,0.4,0.7,0.3,0.6,4.0

In [13]:
df2.tail(5)

     player_id      player_name
481     201163  Wilson Chandler
482    1627812     Yogi Ferrell
483     203897      Zach LaVine
484       2216    Zach Randolph
485       2585    Zaza Pachulia

In [14]:
# We can see df1 and df2 have different columns
# Using the common col of player_id we can merge these dfs!!!

In [15]:
merged_df = pd.merge(df1, df2, on='player_id')

In [16]:
merged_df.sample(10)

,player_id,season_id,gp,age,min,fgm,fga,fg_pct,fg3m,fg3a,...,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts,player_name
501,2760,2010-11,31.0,28.0,32.1,3.7,7.0,0.528,0.0,0.1,...,2.6,0.667,3.2,6.5,1.5,1.3,0.9,1.2,9.1,Anderson Varejao
2249,202689,2015-16,81.0,26.0,35.6,7.0,16.4,0.427,2.2,6.0,...,5.4,0.847,0.7,3.7,5.2,2.1,1.6,0.5,20.9,Kemba Walker
343,2563,2016-17,1.0,36.0,12.0,3.0,8.0,0.375,0.0,2.0,...,4.0,0.750,1.0,1.0,1.0,1.0,0.0,0.0,9.0,Dahntay Jones
423,2571,2005-06,57.0,23.0,27.9,4.8,9.9,0.481,1.5,3.4,...,2.6,0.755,0.5,2.1,2.8,1.6,0.8,0.1,13.1,Leandro Barbosa
2491,203200,2018-19,82.0,30.0,31.8,3.7,9.5,0.386,2.0,5.7,...,1.3,0.896,0.6,3.4,1.8,1.3,1.5,0.4,10.5,Justin Holiday
1377,201575,2011-12,65.0,26.0,26.4,3.6,7.2,0.501,1.5,3.4,...,1.3,0.793,0.5,3.4,1.4,1.0,0.5,0.9,9.8,Brandon Rush
572,2747,2010-11,79.0,25.0,24.9,4.3,9.9,0.435,1.6,4.0,...,2.8,0.738,0.6,3.5,2.2,1.3,1.2,0.2,12.3,JR Smith
2601,203115,2014-15,58.0,24.0,17.0,2.6,6.1,0.425,0.4,1.5,...,1.6,0.787,0.4,2.3,1.4,1.1,0.8,0.3,6.8,Will Barton
1107,201167,2016-17,61.0,31.0,25.9,3.0,6.9,0.440,1.0,2.5,...,1.5,0.892,0.1,1.9,1.3,0.7,0.3,0.1,8.4,Arron Afflalo
2885,203210,2016-17,77.0,27.0,27.3,3.2,6.5,0.500,0.7,1.9,...,2.2,0.802,2.2,4.9,1.1,1.2,0.6,0.4,8.9,JaMychal Green

In [17]:
# to specify certain cols in the merge specify the cols in the merge method parameters

In [18]:
merged_df2 = pd.merge(df2, df1[['player_id', 'season_id', 'ast', 'stl', 'pts']], on='player_id')
merged_df2.sample(10)

      player_id      player_name season_id  ast  stl   pts
169      101106     Andrew Bogut   2009-10  1.8  0.6  15.9
1338       2037   Jamal Crawford   2015-16  2.3  0.7  14.2
502      101112    Channing Frye   2018-19  0.6  0.2   3.6
0       1627773       AJ Hammons   2016-17  0.2  0.0   2.2
2057       2571  Leandro Barbosa   2005-06  2.8  0.8  13.1
449      101139         CJ Miles   2012-13  1.0  0.8  11.2
957        2548      Dwyane Wade   2014-15  4.8  1.2  21.5
1364     201935     James Harden   2009-10  1.8  1.1   9.9
1067     203914      Gary Harris   2017-18  2.9  1.8  17.5
287        2757       Beno Udrih   2015-16  2.6  0.3   4.7

In [19]:
# Can specify right, left, outer merge types using how parameter built into merge method